In [73]:
import numpy as np
import pandas as pd
import os
import warnings
import matplotlib.pyplot as plt
import seaborn as sns
from PIL import Image
import plotly.express as px
import sklearn
import sklearn.model_selection #import train_test_split
from sklearn.neighbors import KNeighborsClassifier

In [74]:
os.listdir('../data/raw')

['17_insurance.csv']

In [75]:
df = pd.read_csv('../data/raw/17_insurance.csv')

In [76]:
df

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [77]:
df.isna().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [78]:
df.duplicated().sum()

np.int64(1)

In [79]:
df.columns

Index(['age', 'sex', 'bmi', 'children', 'smoker', 'region', 'charges'], dtype='object')

In [80]:
df["age"].unique(), df["sex"].unique(),

(array([19, 18, 28, 33, 32, 31, 46, 37, 60, 25, 62, 23, 56, 27, 52, 30, 34,
        59, 63, 55, 22, 26, 35, 24, 41, 38, 36, 21, 48, 40, 58, 53, 43, 64,
        20, 61, 44, 57, 29, 45, 54, 49, 47, 51, 42, 50, 39]),
 array(['female', 'male'], dtype=object))

In [81]:
df["charges"].nunique(),

(1337,)

In [82]:
df.dropna(axis=1, inplace= True)

In [83]:
df.duplicated().sum()

np.int64(1)

In [84]:
# Alle Instanzen von Duplikaten anzeigen
alle_duplikate = df[df.duplicated(keep=False)]

In [85]:
alle_duplikate

     age   sex    bmi  children smoker     region    charges
195   19  male  30.59         0     no  northwest  1639.5631
581   19  male  30.59         0     no  northwest  1639.5631

In [86]:
df_bereinigt =  df.drop_duplicates( keep='last', inplace= True)

In [87]:
df_bereinigt

In [88]:
df.duplicated().sum()

np.int64(0)

In [89]:
df["sex"].value_counts()

sex
male      675
female    662
Name: count, dtype: int64

In [90]:
df["children"].value_counts()

children
0    573
1    324
2    240
3    157
4     25
5     18
Name: count, dtype: int64

In [91]:
df["children"].unique()

array([0, 1, 3, 2, 5, 4])

In [92]:
df["smoker"].value_counts()

smoker
no     1063
yes     274
Name: count, dtype: int64

In [93]:
df["region"].value_counts()

region
southeast    364
southwest    325
northwest    324
northeast    324
Name: count, dtype: int64

# Die Berechnung
- Beispiel: Wiegt jemand 70 kg und ist 1,75 m gross, rechnet man: 
-  70 (1.75 / 1.75) = 22.86 BMI
- unter 18,5	Untergewicht
- 18,5 – 24,9	Normalgewicht
- 25,0 – 29,9   Übergewicht
- ab 30,0	    Adipositas

# ALL Unterweight =  < 18.5 BMI

In [94]:
All_Underweight = df[ df["bmi"] < 18.5].value_counts().sum()

In [95]:
All_Underweight

np.int64(20)

In [96]:
len_all_underweight = All_Underweight

print(f'All Underweight People in df is: {len_all_underweight}')

All Underweight People in df is: 20

In [97]:
df.sample(1)

     age   sex     bmi  children smoker     region     charges
675   45  male  21.375         0     no  northwest  7222.78625

# ALL Unterweight =  MALE

In [98]:
all_male_underweight = df[ df["bmi"] < 18.5] [df["sex"]=='male']

C:\Users\X2-win\AppData\Local\Temp\ipykernel_14640\1803143500.py:1: UserWarning:

Boolean Series key will be reindexed to match DataFrame index.

In [99]:
all_male_underweight.shape[0]

8

In [100]:
all_male_underweight

      age   sex     bmi  children smoker     region      charges
28     23  male  17.385         1     no  northwest   2775.19215
172    18  male  15.960         0     no  northeast   1694.79640
250    18  male  17.290         2    yes  northeast  12829.45510
410    19  male  17.480         0     no  northwest   1621.34020
821    26  male  17.670         0     no  northwest   2680.94930
950    57  male  18.335         0     no  northeast  11534.87265
1205   35  male  17.860         1     no  northwest   5116.50040
1226   38  male  16.815         2     no  northeast   6640.54485

# ALL Unterweight =  FEMALE

In [101]:
all_female_underweight = df[ df["bmi"] < 18.5] [df["sex"]=='female']

C:\Users\X2-win\AppData\Local\Temp\ipykernel_14640\3615630073.py:1: UserWarning:

Boolean Series key will be reindexed to match DataFrame index.

In [102]:
all_female_underweight.shape[0]

12

In [103]:
all_female_underweight

      age     sex     bmi  children smoker     region      charges
128    32  female  17.765         2    yes  northwest  32734.18630
198    51  female  18.050         0     no  northwest   9644.25250
232    19  female  17.800         0     no  southwest   1727.78500
380    27  female  17.955         2    yes  northeast  15006.57945
412    26  female  17.195         2    yes  northeast  14455.64405
428    21  female  16.815         1     no  northeast   3167.45585
680    21  female  17.400         1     no  southwest   2585.26900
1029   37  female  17.290         2     no  northeast   6877.98010
1074   60  female  18.335         0     no  northeast  13204.28565
1085   39  female  18.300         5    yes  southwest  19023.26000
1133   52  female  18.335         0     no  northwest   9991.03765
1286   28  female  17.290         0     no  northeast   3732.62510

# ALL Normal weight =  18.5 - 24.9 BMI

In [104]:
all_mormal_weight = df[ (df["bmi"] >= 18.5) & (df["bmi"] <= 24.9)] [df["sex"]== 'female']

all_mormal_weight

C:\Users\X2-win\AppData\Local\Temp\ipykernel_14640\870501129.py:1: UserWarning:

Boolean Series key will be reindexed to match DataFrame index.

      age     sex     bmi  children smoker     region      charges
26     63  female  23.085         0     no  northeast  14451.83515
48     60  female  24.530         0     no  southeast  12629.89670
58     53  female  22.880         1    yes  southeast  23244.79020
64     20  female  22.420         0    yes  northwest  14711.74380
70     27  female  24.750         0    yes  southeast  16577.77950
...   ...     ...     ...       ...    ...        ...          ...
1302   25  female  20.800         1     no  southwest   3208.78700
1306   29  female  21.850         0    yes  northeast  16115.30450
1314   30  female  23.655         3    yes  northwest  18765.87545
1316   19  female  20.600         0     no  southwest   1731.67700
1328   23  female  24.225         2     no  northeast  22395.74424

[116 rows x 7 columns]

In [105]:
all_mormal_weight.shape

(116, 7)

# Female Normal weight =  18.5 - 24.9 BMI

In [106]:
Normal_weight_Female = df[ (df["bmi"] >= 18.5) & (df["bmi"] <= 24.9)] [df["sex"]== 'female']

Normal_weight_Female

C:\Users\X2-win\AppData\Local\Temp\ipykernel_14640\388978834.py:1: UserWarning:

Boolean Series key will be reindexed to match DataFrame index.

      age     sex     bmi  children smoker     region      charges
26     63  female  23.085         0     no  northeast  14451.83515
48     60  female  24.530         0     no  southeast  12629.89670
58     53  female  22.880         1    yes  southeast  23244.79020
64     20  female  22.420         0    yes  northwest  14711.74380
70     27  female  24.750         0    yes  southeast  16577.77950
...   ...     ...     ...       ...    ...        ...          ...
1302   25  female  20.800         1     no  southwest   3208.78700
1306   29  female  21.850         0    yes  northeast  16115.30450
1314   30  female  23.655         3    yes  northwest  18765.87545
1316   19  female  20.600         0     no  southwest   1731.67700
1328   23  female  24.225         2     no  northeast  22395.74424

[116 rows x 7 columns]

In [107]:
Normal_weight_Female.shape

(116, 7)

# Male Normal weight =  18.5 - 24.9 BMI

In [108]:
Normal_weight_male = df[ (df["bmi"] >= 18.5) & (df["bmi"] <= 24.9)] [df["sex"]== 'male']

Normal_weight_male

C:\Users\X2-win\AppData\Local\Temp\ipykernel_14640\2489107376.py:1: UserWarning:

Boolean Series key will be reindexed to match DataFrame index.

      age   sex     bmi  children smoker     region      charges
3      33  male  22.705         0     no  northwest  21984.47061
15     19  male  24.600         1     no  southwest   1837.23700
17     23  male  23.845         0     no  northeast   2395.17155
35     19  male  20.425         0     no  northwest   1625.43375
37     26  male  20.800         0     no  southwest   2302.30000
...   ...   ...     ...       ...    ...        ...          ...
1265   64  male  23.760         0    yes  southeast  26926.51440
1275   57  male  23.700         0     no  southwest  10959.33000
1292   21  male  23.210         0     no  southeast   1515.34490
1295   20  male  22.000         1     no  southwest   1964.78000
1304   42  male  24.605         2    yes  northeast  21259.37795

[106 rows x 7 columns]

In [109]:
Normal_weight_male.shape

(106, 7)

# All Overweight =  25 - 29.9 BMI

In [110]:
all_Overweight = df[ (df["bmi"] >= 24.91) & (df["bmi"] <= 29.9)]

In [111]:
all_Overweight.shape

(380, 7)

In [112]:
all_Overweight

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
4      32    male  28.880         0     no  northwest   3866.85520
5      31  female  25.740         0     no  southeast   3756.62160
7      37  female  27.740         3     no  northwest   7281.50560
8      37    male  29.830         2     no  northeast   6406.41070
...   ...     ...     ...       ...    ...        ...          ...
1321   62    male  26.695         0    yes  northeast  28101.33305
1324   31    male  25.935         1     no  northwest   4239.89265
1330   57  female  25.740         2     no  southeast  12629.16560
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[380 rows x 7 columns]

# All Overweight  FEMALE =  25 - 29.9 BMI

In [113]:
all_Overweight_female = df[ (df["bmi"] >= 24.91) & (df["bmi"] <= 29.9)][df ["sex"] == 'female']

all_Overweight_female

C:\Users\X2-win\AppData\Local\Temp\ipykernel_14640\3294873113.py:1: UserWarning:

Boolean Series key will be reindexed to match DataFrame index.

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
5      31  female  25.740         0     no  southeast   3756.62160
7      37  female  27.740         3     no  northwest   7281.50560
9      60  female  25.840         0     no  northwest  28923.13692
11     62  female  26.290         0    yes  southeast  27808.72510
...   ...     ...     ...       ...    ...        ...          ...
1311   33  female  26.695         0     no  northwest   4571.41305
1319   39  female  26.315         2     no  northwest   7201.70085
1330   57  female  25.740         2     no  southeast  12629.16560
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[192 rows x 7 columns]

In [114]:
all_Overweight_female.shape

(192, 7)

# All Overweight MALE =  25 - 29.9 BMI

In [115]:
all_Overweight_male = df[ (df["bmi"] >= 24.91) & (df["bmi"] <= 29.9)][df ["sex"] == 'male']

all_Overweight_male

C:\Users\X2-win\AppData\Local\Temp\ipykernel_14640\1993063132.py:1: UserWarning:

Boolean Series key will be reindexed to match DataFrame index.

      age   sex     bmi  children smoker     region      charges
4      32  male  28.880         0     no  northwest   3866.85520
8      37  male  29.830         2     no  northeast   6406.41070
10     25  male  26.220         0     no  northeast   2721.32080
24     37  male  28.025         2     no  northwest   6203.90175
33     63  male  28.310         0     no  northwest  13770.09790
...   ...   ...     ...       ...    ...        ...          ...
1307   32  male  28.120         4    yes  northwest  21472.47880
1310   42  male  26.315         1     no  northwest   6940.90985
1315   18  male  28.310         1     no  northeast  11272.33139
1321   62  male  26.695         0    yes  northeast  28101.33305
1324   31  male  25.935         1     no  northwest   4239.89265

[188 rows x 7 columns]

In [116]:
all_Overweight_male

      age   sex     bmi  children smoker     region      charges
4      32  male  28.880         0     no  northwest   3866.85520
8      37  male  29.830         2     no  northeast   6406.41070
10     25  male  26.220         0     no  northeast   2721.32080
24     37  male  28.025         2     no  northwest   6203.90175
33     63  male  28.310         0     no  northwest  13770.09790
...   ...   ...     ...       ...    ...        ...          ...
1307   32  male  28.120         4    yes  northwest  21472.47880
1310   42  male  26.315         1     no  northwest   6940.90985
1315   18  male  28.310         1     no  northeast  11272.33139
1321   62  male  26.695         0    yes  northeast  28101.33305
1324   31  male  25.935         1     no  northwest   4239.89265

[188 rows x 7 columns]

# All XXL Obesity =  > 30 BMI

In [117]:
all_XXL_Obesity = df[ (df["bmi"] > 29.91) ]

all_XXL_Obesity

      age     sex    bmi  children smoker     region      charges
1      18    male  33.77         1     no  southeast   1725.55230
2      28    male  33.00         3     no  southeast   4449.46200
6      46  female  33.44         1     no  southeast   8240.58960
12     23    male  34.40         0     no  southwest   1826.84300
13     56  female  39.82         0     no  southeast  11090.71780
...   ...     ...    ...       ...    ...        ...          ...
1331   23  female  33.40         0     no  southwest  10795.93733
1332   52  female  44.70         3     no  southwest  11411.68500
1333   50    male  30.97         3     no  northwest  10600.54830
1334   18  female  31.92         0     no  northeast   2205.98080
1335   18  female  36.85         0     no  southeast   1629.83350

[715 rows x 7 columns]

In [118]:
all_XXL_Obesity.shape

(715, 7)

# All XXL Obesity FEMALE =  > 30 BMI

In [119]:
all_XXL_Obesity_female = df[ (df["bmi"] > 29.91) ][df["sex"]== 'female']

all_XXL_Obesity_female

C:\Users\X2-win\AppData\Local\Temp\ipykernel_14640\3517670465.py:1: UserWarning:

Boolean Series key will be reindexed to match DataFrame index.

      age     sex     bmi  children smoker     region      charges
6      46  female  33.440         1     no  southeast   8240.58960
13     56  female  39.820         0     no  southeast  11090.71780
16     52  female  30.780         1     no  northeast  10797.33620
20     60  female  36.005         0     no  northeast  13228.84695
21     30  female  32.400         1     no  southwest   4149.73600
...   ...     ...     ...       ...    ...        ...          ...
1326   42  female  32.870         0     no  northeast   7050.02130
1331   23  female  33.400         0     no  southwest  10795.93733
1332   52  female  44.700         3     no  southwest  11411.68500
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350

[342 rows x 7 columns]

In [120]:
all_XXL_Obesity_female.shape

(342, 7)

# All XXL Obesity MALE =  > 30 BMI

In [121]:
all_XXL_Obesity_male = df[ (df["bmi"] > 29) ][df["sex"]== 'male']

all_XXL_Obesity_male

C:\Users\X2-win\AppData\Local\Temp\ipykernel_14640\4176953355.py:1: UserWarning:

Boolean Series key will be reindexed to match DataFrame index.

      age   sex     bmi  children smoker     region      charges
1      18  male  33.770         1     no  southeast   1725.55230
2      28  male  33.000         3     no  southeast   4449.46200
8      37  male  29.830         2     no  northeast   6406.41070
12     23  male  34.400         0     no  southwest   1826.84300
14     27  male  42.130         0    yes  southeast  39611.75770
...   ...   ...     ...       ...    ...        ...          ...
1322   62  male  38.830         0     no  southeast  12981.34570
1325   61  male  33.535         0     no  northeast  13143.33665
1327   51  male  30.030         1     no  southeast   9377.90470
1329   52  male  38.600         2     no  southwest  10325.20600
1333   50  male  30.970         3     no  northwest  10600.54830

[408 rows x 7 columns]

In [122]:
all_XXL_Obesity_male.shape

(408, 7)

In [123]:
All_Underweight

np.int64(20)

# Alle Zusammen Female and Male

In [154]:
df["sex"].value_counts().sum()

np.int64(1337)

In [152]:
df[ df["sex"] == "female"].value_counts().sum()

np.int64(662)

In [153]:
df[ df["sex"] == "male"].value_counts().sum()

np.int64(675)

In [124]:
df["bmi"].isna().sum()

np.int64(0)

### Hier die neu erstellte All Unterweight in die df Liste hinzufügen

In [125]:
# 1. Underweight
df.loc[df["bmi"] < 18.5, 'Class_weights'] = 'Underweight'

# 2. Normal weight
df.loc[(df["bmi"] >= 18.5) & (df["bmi"] <= 24.9), 'Class_weights'] = 'Normal weight'

# 3. Overweight
df.loc[(df["bmi"] >= 24.91) & (df["bmi"] <= 29.9), 'Class_weights'] = 'Overweight'

# 4. xxl Overweight or Adipositas
df.loc[df["bmi"] >= 29.91 , 'Class_weights'] = 'xxl Overweight'

In [126]:
df.sample(2)

     age     sex     bmi  children smoker     region     charges Class_weights
134   20  female  28.785         0     no  northeast  2457.21115    Overweight
410   19    male  17.480         0     no  northwest  1621.34020   Underweight

In [127]:
df["Class_weights"].value_counts()

Class_weights
xxl Overweight    715
Overweight        380
Normal weight     222
Underweight        20
Name: count, dtype: int64

In [128]:
df["Class_weights"].isna().sum()

np.int64(0)

In [129]:
df [ df["Class_weights"].isna()]

Empty DataFrame
Columns: [age, sex, bmi, children, smoker, region, charges, Class_weights]
Index: []

In [130]:
df[ df["Class_weights"]== 'xxl Overweight'][df["sex"]=='female'].shape

C:\Users\X2-win\AppData\Local\Temp\ipykernel_14640\4076404671.py:1: UserWarning:

Boolean Series key will be reindexed to match DataFrame index.

(342, 8)

In [131]:
df[ df["Class_weights"]== 'xxl Overweight'][df["sex"]=='male'].shape

C:\Users\X2-win\AppData\Local\Temp\ipykernel_14640\2276038345.py:1: UserWarning:

Boolean Series key will be reindexed to match DataFrame index.

(373, 8)

In [132]:
df[ df["Class_weights"]== 'Overweight'][df["sex"]=='female'].shape

C:\Users\X2-win\AppData\Local\Temp\ipykernel_14640\3364417283.py:1: UserWarning:

Boolean Series key will be reindexed to match DataFrame index.

(192, 8)

In [133]:
df[ df["Class_weights"]== 'Overweight'][df["sex"]=='male'].shape

C:\Users\X2-win\AppData\Local\Temp\ipykernel_14640\3863625085.py:1: UserWarning:

Boolean Series key will be reindexed to match DataFrame index.

(188, 8)

In [134]:
df[ df["Class_weights"]== 'Normal weight'][df["sex"]=='female'].shape

C:\Users\X2-win\AppData\Local\Temp\ipykernel_14640\3854825804.py:1: UserWarning:

Boolean Series key will be reindexed to match DataFrame index.

(116, 8)

In [141]:
df[ df["Class_weights"]== 'Normal weight'][df["sex"]=='male'].shape

C:\Users\X2-win\AppData\Local\Temp\ipykernel_14640\1993574778.py:1: UserWarning:

Boolean Series key will be reindexed to match DataFrame index.

(106, 8)

In [136]:
df[ df["Class_weights"]== 'Underweight'][df["sex"]=='female'].shape

C:\Users\X2-win\AppData\Local\Temp\ipykernel_14640\1616806947.py:1: UserWarning:

Boolean Series key will be reindexed to match DataFrame index.

(12, 8)

In [137]:
df[ df["Class_weights"]== 'Underweight'][df["sex"]=='male'].shape

C:\Users\X2-win\AppData\Local\Temp\ipykernel_14640\2477244110.py:1: UserWarning:

Boolean Series key will be reindexed to match DataFrame index.

(8, 8)

In [138]:
px.histogram(df, x= 'Class_weights'  )

In [139]:
px.pie(df,  names='Class_weights' )

In [140]:
# Export to the list
df.to_csv('../data/cleaned data/cleaned_17_insurance.csv', index= False)